name: Euria Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_dependencies:
    uses: infomaniak/.github/.github/workflows/ai-review.yml
    secrets: inherit